### ISSUE TITLE
Migrate to new YAML syntax for workflow instructions

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/actions-wordpress#15]
The new YAML syntax is taking over and the actions here should get migrated from HCL to YAML syntax when possible.

https://help.github.com/en/articles/migrating-github-actions-from-hcl-syntax-to-yaml-syntax

**Comment by helen** [comment]
Thanks for opening this issue @sc0ttkclark - I'm working on making sure we use the actual `tag` action instead of just `push`, previously only `push` was enabled for public repos but that's since changed so I want to update this wholesale!

**Comment by sc0ttkclark** [comment]
:dance-attack: thanks!

**Comment by 2ndkauboy** [comment]
I've just used your GitHub action yesterday and had to migrate the HCL files to the YAML syntax. I used the migration tool from GitHub. You can find the YAML files here: https://github.com/2ndkauboy/SyntaxHighlighter-Evolved-SASS-Brush/tree/master/.github/workflows

**Comment by helen** [comment]
@sc0ttkclark @2ndkauboy If y'all have a moment, would appreciate any thoughts on the correctness and readability of #20 :)

**Comment by 2ndkauboy** [comment]
Looks good to me!

**Comment by 2ndkauboy** [comment]
I just checked your new YAML files with my plugin by updating only the readme and it looks really good. Only the readme/assets action fired and was successful! 🙌

**Comment by helen** [comment]
@2ndkauboy @sc0ttkclark You will probably want to update the plugin deploy workflow to use the new/improved tag filtering syntax, I've updated the documentation here: https://github.com/10up/action-wordpress-plugin-deploy

**Comment by sc0ttkclark** [comment]
Just ran this successfully. In my case, I didn't have any npm build process that needed to run so it would fail to deploy because of npm errors. Once I removed that section it ran perfectly.

**Comment by sc0ttkclark** [comment]
I should note that this was probably the fastest deploy I've ever done! Not talking about steps (we had automation before) but in terms of SVN this whole process ran for 1m 38s, which only 30s was SVN. That's awesome, thank you very much for helping speed up my workflow! :)

**Comment by helen** [comment]
@sc0ttkclark Yay!!! We are actually discussing documentation of multiple examples over in https://github.com/10up/action-wordpress-plugin-deploy/issues/5 - I am worried about exactly what you experienced, which is that as people are getting these things set up for the first time, they won't quite understand that they may need to remove stuff from the sample workflow file, so maybe it should be a barebones example and link off to more examples in a separate document.

**Comment by sc0ttkclark** [comment]
Yeah I like that idea, knowing the easy syntax to include npm processes is super handy to know how to put the two together
