### ISSUE TITLE
Action: Create pull request to bump Tested Up To Tag when WordPress releases a new version

### ISSUE THREAD

**Issue by claytoncollie** [10up/actions-wordpress#32]
**Is your enhancement related to a problem? Please describe.**
I have 5 small plugins that are feature complete. They add a settings field to the option-general.php page so the admin can paste in their Google Analytics, Tag Manager, Facebook Pixel, etc. The plugins contain 2 files and only a handful of functions. I do not plan on adding new functionality or changing the code for a very long time. But the annoying thing is that if I do not keep on top of the readme.txt tested up to tag, wordpress.org will flag my plugin as out of date :(

**Describe the solution you'd like**
I would like an action to creates a cron job, pings the wordpress.org servers to check if there is a new version of WordPress, and if there is, creates a pull request to my main branch with Tested Up bumped to the latest version. I see myself adding some small unit or acceptance tests in there to make sure the plugin activates on said version but the general flow can work without test. This feels a lot like dependabot...but for WordPress.

**Additional context**
Here is my example plugin - https://github.com/claytoncollie/tracking-code-for-google-analytics

**Comment by jeffpaul** [comment]
@claytoncollie we can probably chat about your ideas on this here, though maybe we can grab time to chat on zoom to sort out your ideas and then I can document that back here.

**Comment by cadic** [comment]
Looks like [skaut/wordpress-version-checker](https://github.com/marketplace/actions/wordpress-version-checker) do the job.

It will create an issue if the plugin's "Tested up to" does not match the latest WP core.

**Comment by claytoncollie** [comment]
Thanks for sending this over @cadic 

I think this action can be used in conjunction with some end-to-end tests so that when this cron job runs and finds the stable date is out of date, we can trigger an end-to-end test with the lastest WordPress version. If all tests pass then create a PR to bump the version. 

This is probably all I need from this ticket so I am going to close it for now.

**Comment by jeffpaul** [comment]
@cadic what do you think about testing that Action in one of our repos (ideally one that's not yet bumped to WP 6.0) with it configured to run once a week though not sure we need to trigger on pushes to `trunk` (also not sure about `develop` either as once a week might suffice)?  Thoughts?

**Comment by cadic** [comment]
@jeffpaul testing it with https://github.com/10up/windows-azure-storage

1. [x] Action added to the PR https://github.com/10up/windows-azure-storage/pull/160
2. [x] Issue has been created automatically on pull request https://github.com/10up/windows-azure-storage/issues/161
3. [x] Issue should be deleted/closed after "Bump" PR is merged https://github.com/10up/windows-azure-storage/pull/162 (the first PR should be already merged or the action needs to be manually triggered from pull request)

**Comment by cadic** [comment]
The original action I am referring to needs some improvements

- It does store node_modules in the repo
- The issue template is hardcoded

Probably we could contribute or fork it

**Comment by cadic** [comment]
@jeffpaul the next steps:

1. Approve/merge https://github.com/10up/windows-azure-storage/pull/160 (Don't close https://github.com/10up/windows-azure-storage/issues/159 yet)
2. Approve/merge https://github.com/10up/windows-azure-storage/pull/162
3. The issue https://github.com/10up/windows-azure-storage/issues/161 should be auto-closed on push to develop after step 2
4. We could close https://github.com/10up/windows-azure-storage/issues/159 now
