### ISSUE TITLE
Sections duplicates

### ISSUE THREAD

**Issue by nikitasinelnikov** [10up/actions-wordpress#33]
**Describe the bug**
The individual hook page contains 3 repeated sections with hook details https://www.screencast.com/t/2idQJM25

**Steps to Reproduce**
1. I have made the following steps from this article https://github.com/10up/actions-wordpress/blob/stable/hookdocs-workflow.md
2. GH Action has been successfully completed and I have the "gh-pages" branch in my repo for now.
3. When I open the hooks docs, I see the 3 sections with hook content instead of  1. https://www.screencast.com/t/2idQJM25
4. I have tried different ways and layouts. Then finally, tried to use the default layout from JSDoc https://www.screencast.com/t/qW4CXayhWO58

**Expected behavior**
I need to have only one section.

**Additional context**
There are my attached files related to hookdoc:
https://www.dropbox.com/s/mn9egx0d4x1c3lg/hookdoc-conf.json?dl=0
https://www.dropbox.com/s/jhsezqvyd4lz5c3/build-docs.yml?dl=0
https://www.dropbox.com/s/xz1atowlfl88vyv/layout.tmpl?dl=0

**Comment by dinhtungdu** [comment]
Hi @nikitasinelnikov Is the issue happening for every hook? Can you set up a public repo with your plugin and configuration? It's easier for us to trace the bug.

**Comment by nikitasinelnikov** [comment]
Hi @dinhtungdu 

Thanks for your prompt answer! Yes, I have placed a few hook comments in JSDoc style and the issue happening for each of these hooks. You may check this repo https://github.com/ultimatemember/jobboardwp I have made it public for now.

Best Regards!

**Comment by dinhtungdu** [comment]
@nikitasinelnikov You can fix your issue by removing the `includes` setting [here](https://github.com/ultimatemember/jobboardwp/blob/master/hookdoc-conf.json#L9-L13). I'm not sure why it causes the issue because I'm not very familiar with jsdocs. I will update the example to prevent confusion. Thanks so much for reporting this issue.

**Comment by dinhtungdu** [comment]
Another way to fix your issue:

hookdoc-conf.json:
```
...
  "source": {
    "include": [
      "./"
    ],
    "exclude": [
      "node_modules"
    ],
    "includePattern": ".+\\.(php)?$"
  },
...
```

package.json:
```
...
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "build:docs": "rm -rf hookdocs/ && jsdoc -c hookdoc-conf.json"
  }
...
```

**Comment by nikitasinelnikov** [comment]
Hi @dinhtungdu 

It works like a charm, thanks a lot!

Have a nice day,
Best Regards!
