### ISSUE TITLE
Please do the tag before the commit.

### ISSUE THREAD

**Issue by Otto42** [10up/actions-wordpress#4]
It would be nice if you didn't create two commits by doing a remote svn cp command after the initial trunk commit. 

You can checkout the root folder (shallowly, if you like, for speed) and then do the trunk update followed by a local svn cp command to tag the version. Then you can commit the whole change all at once. 

This prevents that middle moment when the readme in trunk points to a tag that you haven't created yet. Both trunk and the tagged version are sent at the same time. 

Despite what some think, this doesn't result in extra data use. Svn knows how to deal with local cp commands.

**Comment by helen** [comment]
Sure thing, will take a look at changing that soon.
