### ISSUE TITLE
Assets in an assets branch

### ISSUE THREAD

**Issue by sc0ttkclark** [10up/actions-wordpress#6]
It seems pretty common for assets to be stored in the assets branch of a repo. Any plans to support using the assets branch instead of a directory in the tagged code?

**Comment by helen** [comment]
I haven't planned on it - why do people do that? Because of Deployer? I think that's a little bit of an odd pattern to maintain although I can see its convenience.

**Comment by sc0ttkclark** [comment]
That's okay, I'm sure people can switch over to the assets directory in the future. Just figured I'd check before making those changes.
