### ISSUE TITLE
support .svnignore

### ISSUE THREAD

**Issue by pfefferle** [10up/actions-wordpress#9]
I love the idea of a `.svnignore` file, implemented in the [travis2wpplugin](https://github.com/miya0001/travis2wpplugin) by @miya0001: https://github.com/miya0001/travis2wpplugin#svnignore

It allows to ignore meta-files that might make sense in the Git repo, but should not be part of the final release (for example grunt, composer, npm, ... files)

**Comment by helen** [comment]
I would really love to figure out if there's a way to consolidate ignore files - right now you can use `.gitattributes` but it has its own syntax for directives. Another Action I've been working on uses an rsync filter file which is yet another syntax. There are also things like `.distignore`. So I suppose my questions are - why `.svnignore`, and do other methods not work for you for any reason?

**Comment by pfefferle** [comment]
oh, haven't thought about the `.gitattributes` file... this should fit for my needs...

thanks for the hint!
